// PNG parts registry — the ONE place you wire a generated image into the app.
//
// Metro (the bundler) can't load an asset unless it's literally `require()`d in
// source, so dynamic `require("../assets/parts/" + id)` does NOT work. Instead, add
// one line here per PNG you drop into `assets/parts/`. The key is `"{category}/{id}"`
// and must match the catalog id in `dm.ts`.
//
// Example — after you save `assets/parts/hair/waves.png`, add:
//
//   "hair/wavyM": require("../../assets/parts/hair/wavyM.png"),
//
// Start with `body/balanced` (the base body), then hair, then the rest.

export const PARTS: Record<string, number> = {
  // Contact-sheet-approved P0 catalog (2026-07-03) — generated by the art-gen
  // pipeline; ingest-approved.mjs emits these lines. Only approved art enters.
  // skin/base ships as the registration master in assets/, deliberately unlisted.
  "aac/board": require("../../assets/parts/aac/board.png"),
  "aac/letterboard": require("../../assets/parts/aac/letterboard.png"),
  "aac/tablet": require("../../assets/parts/aac/tablet.png"),
  "accessory/headscarf": require("../../assets/parts/accessory/headscarf.png"),
  "body/broad": require("../../assets/parts/body/broad.png"),
  "body/curves": require("../../assets/parts/body/curves.png"),
  "body/full": require("../../assets/parts/body/full.png"),
  "body/lean": require("../../assets/parts/body/lean.png"),
  "bottom/barrelJean": require("../../assets/parts/bottom/barrelJean.png"),
  "bottom/cargo": require("../../assets/parts/bottom/cargo.png"),
  "bottom/joggers": require("../../assets/parts/bottom/joggers.png"),
  "bottom/leggings": require("../../assets/parts/bottom/leggings.png"),
  "bottom/midiSkirt": require("../../assets/parts/bottom/midiSkirt.png"),
  "bottom/shorts": require("../../assets/parts/bottom/shorts.png"),
  "bottom/straightJean": require("../../assets/parts/bottom/straightJean.png"),
  "bottom/wideDenim": require("../../assets/parts/bottom/wideDenim.png"),
  "bottom/wideTrouser": require("../../assets/parts/bottom/wideTrouser.png"),
  "brow/bold": require("../../assets/parts/brow/bold.png"),
  "brow/fine": require("../../assets/parts/brow/fine.png"),
  "brow/soft": require("../../assets/parts/brow/soft.png"),
  "brow/straight": require("../../assets/parts/brow/straight.png"),
  "carry/backpack": require("../../assets/parts/carry/backpack.png"),
  "carry/crossbody": require("../../assets/parts/carry/crossbody.png"),
  "carry/tote": require("../../assets/parts/carry/tote.png"),
  "eye/almond": require("../../assets/parts/eye/almond.png"),
  "eye/hooded": require("../../assets/parts/eye/hooded.png"),
  "eye/wide": require("../../assets/parts/eye/wide.png"),
  "faceShape/diamond": require("../../assets/parts/faceShape/diamond.png"),
  "faceShape/heart": require("../../assets/parts/faceShape/heart.png"),
  "faceShape/long": require("../../assets/parts/faceShape/long.png"),
  "faceShape/oval": require("../../assets/parts/faceShape/oval.png"),
  "faceShape/round": require("../../assets/parts/faceShape/round.png"),
  "faceShape/square": require("../../assets/parts/faceShape/square.png"),
  "feature/birthmark": require("../../assets/parts/feature/birthmark.png"),
  "feature/blush": require("../../assets/parts/feature/blush.png"),
  "feature/freckles": require("../../assets/parts/feature/freckles.png"),
  "feature/scar": require("../../assets/parts/feature/scar.png"),
  "feature/vitiligo": require("../../assets/parts/feature/vitiligo.png"),
  "glasses/rect": require("../../assets/parts/glasses/rect.png"),
  "glasses/round": require("../../assets/parts/glasses/round.png"),
  "hair/bigBlowout": require("../../assets/parts/hair/bigBlowout.png"),
  "hair/bob": require("../../assets/parts/hair/bob.png"),
  "hair/braid": require("../../assets/parts/hair/braid.png"),
  "hair/clawClip": require("../../assets/parts/hair/clawClip.png"),
  "hair/curtain": require("../../assets/parts/hair/curtain.png"),
  "hair/definedCurls": require("../../assets/parts/hair/definedCurls.png"),
  "hair/halfUp": require("../../assets/parts/hair/halfUp.png"),
  "hair/highBun": require("../../assets/parts/hair/highBun.png"),
  "hair/highPony": require("../../assets/parts/hair/highPony.png"),
  "hair/layers": require("../../assets/parts/hair/layers.png"),
  "hair/lowBun": require("../../assets/parts/hair/lowBun.png"),
  "hair/lowPony": require("../../assets/parts/hair/lowPony.png"),
  "hair/messyBun": require("../../assets/parts/hair/messyBun.png"),
  "hair/pigtails": require("../../assets/parts/hair/pigtails.png"),
  "hair/sleekBun": require("../../assets/parts/hair/sleekBun.png"),
  "hair/straightL": require("../../assets/parts/hair/straightL.png"),
  "hair/wavyM": require("../../assets/parts/hair/wavyM.png"),
  "hearing/ci_both": require("../../assets/parts/hearing/ci_both.png"),
  "hearing/ha_l": require("../../assets/parts/hearing/ha_l.png"),
  "hearing/ha_r": require("../../assets/parts/hearing/ha_r.png"),
  "lip/bow": require("../../assets/parts/lip/bow.png"),
  "lip/full": require("../../assets/parts/lip/full.png"),
  "lip/petite": require("../../assets/parts/lip/petite.png"),
  "lip/soft": require("../../assets/parts/lip/soft.png"),
  "lip/wide": require("../../assets/parts/lip/wide.png"),
  "makeup/bold": require("../../assets/parts/makeup/bold.png"),
  "makeup/glam": require("../../assets/parts/makeup/glam.png"),
  "makeup/graphic": require("../../assets/parts/makeup/graphic.png"),
  "makeup/lashes": require("../../assets/parts/makeup/lashes.png"),
  "makeup/liner": require("../../assets/parts/makeup/liner.png"),
  "makeup/natural": require("../../assets/parts/makeup/natural.png"),
  "makeup/smoky": require("../../assets/parts/makeup/smoky.png"),
  "mobility/cane": require("../../assets/parts/mobility/cane.png"),
  "mobility/walker": require("../../assets/parts/mobility/walker.png"),
  "mobility/wheelchair": require("../../assets/parts/mobility/wheelchair.png"),
  "nose/button": require("../../assets/parts/nose/button.png"),
  "nose/long": require("../../assets/parts/nose/long.png"),
  "nose/narrow": require("../../assets/parts/nose/narrow.png"),
  "nose/rounded": require("../../assets/parts/nose/rounded.png"),
  "nose/wide": require("../../assets/parts/nose/wide.png"),
  "shoe/classicSneaker": require("../../assets/parts/shoe/classicSneaker.png"),
  "shoe/loafer": require("../../assets/parts/shoe/loafer.png"),
  "shoe/mary": require("../../assets/parts/shoe/mary.png"),
  "shoe/runner": require("../../assets/parts/shoe/runner.png"),
  "shoe/slide": require("../../assets/parts/shoe/slide.png"),
  "shoe/sneaker": require("../../assets/parts/shoe/sneaker.png"),
  "tool/noiseHeadphones": require("../../assets/parts/tool/noiseHeadphones.png"),
  "top/boxyTee": require("../../assets/parts/top/boxyTee.png"),
  "top/button": require("../../assets/parts/top/button.png"),
  "top/cardigan": require("../../assets/parts/top/cardigan.png"),
  "top/drapedShirt": require("../../assets/parts/top/drapedShirt.png"),
  "top/hoodie": require("../../assets/parts/top/hoodie.png"),
  "top/longSleeveTee": require("../../assets/parts/top/longSleeveTee.png"),
  "top/plainTee": require("../../assets/parts/top/plainTee.png"),
  "top/ribTank": require("../../assets/parts/top/ribTank.png"),
  "top/sweater": require("../../assets/parts/top/sweater.png"),
  "top/sweatshirt": require("../../assets/parts/top/sweatshirt.png"),
};

export const hasPart = (key: string): boolean =>
  Object.prototype.hasOwnProperty.call(PARTS, key);

export const partRef = (key: string): number | undefined => PARTS[key];

export const partCount = (): number => Object.keys(PARTS).length;
