// GENERATED by tools/art-gen/gen-svg-registry.mjs — DO NOT EDIT.
// Regenerate: node tools/art-gen/trace-svg.mjs && node tools/art-gen/gen-svg-registry.mjs
//
// SVG parts registry — vector twin of registry.ts (Story 2.4). Each value is the
// part's inner <g> markup in the canonical 1024x1536 full-frame space (registration
// baked in — composites 1:1 with zero per-part offset). Keys are exact catalog ids.
// Only trace-QA-passed parts enter (154 parts, 879 KB on 2026-07-05).
// Tint at composite time = per-fill multiply (SvgPartsFigure); parts stay neutral here.
// Plain .js + .d.ts so Metro, tsc, and Node gate scripts all read the same module.

export declare const PARTS_SVG: Record<string, string>;
export declare const PARTS_SVG_BBOX: Record<string, readonly number[]>;
export declare const hasSvgPart: (key: string) => boolean;
export declare const svgPartRef: (key: string) => string | undefined;
export declare const svgPartCount: () => number;
